name: Windows echo Workflow

on:
  push:
    branches:
      - main

jobs:
  please:
    runs-on: ["self-hosted", "Windows"]
    steps:
      - name: test
#         run: uname > aaaaaaa.txt
#         run: uname > /mnt/c/Users/YK.KWON/Desktop/aaaa.txt
#         run: uname > /mnt/c/Users/YK.KWON/Desktop
        run: wsl uname > C:\Users\YK.KWON\Desktop\git-bash\aaaa.txt
#         shell: wsl
