name: Windows echo Workflow

on:
  push:
    branches:
      - main

jobs:
  echo:
    runs-on: ["Windows", "self-hosted"]
    steps:
      - name: test
        shell: "C:/Program Files/Git/bin/bash.exe {0}"
        run: |
          mkdir sample_dir
