name: Windows echo Workflow

on:
  push:
    branches:
      - main

jobs:
  echo:
#     runs-on: ["Windows", "self-hosted"]
    runs-on: windows-latest
    steps:
      - name: test
#         shell: C:\\Program\ Files\\Git\\git-bash.exe -c {0}
        shell: bash
        run: |
          mkdir sample_dir
